//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this information..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account manager(s) successfully added..
        /// </summary>
        internal static string AccountManagerSuccessAdd {
            get {
                return ResourceManager.GetString("AccountManagerSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account manager successfully removed..
        /// </summary>
        internal static string AccountManagerSuccessRemove {
            get {
                return ResourceManager.GetString("AccountManagerSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name is already taken..
        /// </summary>
        internal static string AccountNameDuplicate {
            get {
                return ResourceManager.GetString("AccountNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully activated..
        /// </summary>
        internal static string AccountSuccessActivate {
            get {
                return ResourceManager.GetString("AccountSuccessActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully added..
        /// </summary>
        internal static string AccountSuccessAdd {
            get {
                return ResourceManager.GetString("AccountSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully deactivated..
        /// </summary>
        internal static string AccountSuccessDeactivate {
            get {
                return ResourceManager.GetString("AccountSuccessDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully deleted..
        /// </summary>
        internal static string AccountSuccessDelete {
            get {
                return ResourceManager.GetString("AccountSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully updated..
        /// </summary>
        internal static string AccountSuccessUpdate {
            get {
                return ResourceManager.GetString("AccountSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent not found..
        /// </summary>
        internal static string AgentNotFound {
            get {
                return ResourceManager.GetString("AgentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent successfully added..
        /// </summary>
        internal static string AgentSuccessAdd {
            get {
                return ResourceManager.GetString("AgentSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent successfully edited assigned teams..
        /// </summary>
        internal static string AgentSuccessEditAssTeams {
            get {
                return ResourceManager.GetString("AgentSuccessEditAssTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent successfully removed..
        /// </summary>
        internal static string AgentSuccessRemove {
            get {
                return ResourceManager.GetString("AgentSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User attendance status successfully updated..
        /// </summary>
        internal static string AttStatusUpdateSuccess {
            get {
                return ResourceManager.GetString("AttStatusUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already used up all your breaks..
        /// </summary>
        internal static string BreakLimit {
            get {
                return ResourceManager.GetString("BreakLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not found..
        /// </summary>
        internal static string ClientNotFound {
            get {
                return ResourceManager.GetString("ClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client(s) successfully added..
        /// </summary>
        internal static string ClientSuccessAdd {
            get {
                return ResourceManager.GetString("ClientSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client successfully removed..
        /// </summary>
        internal static string ClientSuccessRemove {
            get {
                return ResourceManager.GetString("ClientSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process request failed due to data not found..
        /// </summary>
        internal static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in used..
        /// </summary>
        internal static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email notification successfully updated..
        /// </summary>
        internal static string EmailNotificationSuccessUpdate {
            get {
                return ResourceManager.GetString("EmailNotificationSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not registered..
        /// </summary>
        internal static string EmailNotReg {
            get {
                return ResourceManager.GetString("EmailNotReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has already been approved by {0} on {1} at {2}..
        /// </summary>
        internal static string EODAlreadyApproved {
            get {
                return ResourceManager.GetString("EODAlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has already been denied by {0} on {1} at {2}..
        /// </summary>
        internal static string EODAlreadyDenied {
            get {
                return ResourceManager.GetString("EODAlreadyDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOD Report approved..
        /// </summary>
        internal static string EODApproved {
            get {
                return ResourceManager.GetString("EODApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOD Report denied..
        /// </summary>
        internal static string EODDenied {
            get {
                return ResourceManager.GetString("EODDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding EOD report for this chronological data is &quot;DENIED&quot; Aprroval..
        /// </summary>
        internal static string EODDeniedStatusNote {
            get {
                return ResourceManager.GetString("EODDeniedStatusNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized for this action..
        /// </summary>
        internal static string EODNotAuthorized {
            get {
                return ResourceManager.GetString("EODNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corresponding EOD report for this chronological data is still &quot;PENDING&quot; for Aprroval..
        /// </summary>
        internal static string EODPendingStatusNote {
            get {
                return ResourceManager.GetString("EODPendingStatusNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in processing your request please contact your System Administrator..
        /// </summary>
        internal static string EODProcessError {
            get {
                return ResourceManager.GetString("EODProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not added a role..
        /// </summary>
        internal static string ErrorAddToRole {
            get {
                return ResourceManager.GetString("ErrorAddToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is no longer assigned to you. please refresh page..
        /// </summary>
        internal static string InvalidTaskToActivate {
            get {
                return ResourceManager.GetString("InvalidTaskToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address already exists..
        /// </summary>
        internal static string IPWhitelistEntryError {
            get {
                return ResourceManager.GetString("IPWhitelistEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address successfully added to whitelist..
        /// </summary>
        internal static string IPWhitelistEntrySuccessAdd {
            get {
                return ResourceManager.GetString("IPWhitelistEntrySuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address successfully updated from whitelist..
        /// </summary>
        internal static string IPWhitelistEntrySuccessUpdate {
            get {
                return ResourceManager.GetString("IPWhitelistEntrySuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Agent not found..
        /// </summary>
        internal static string LANotFound {
            get {
                return ResourceManager.GetString("LANotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Agent(s)  successfully added..
        /// </summary>
        internal static string LASuccessAdd {
            get {
                return ResourceManager.GetString("LASuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Agent successfully edited assigned teams..
        /// </summary>
        internal static string LASuccessEditAssTeams {
            get {
                return ResourceManager.GetString("LASuccessEditAssTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Agent successfully removed..
        /// </summary>
        internal static string LASuccessRemove {
            get {
                return ResourceManager.GetString("LASuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location details already exist..
        /// </summary>
        internal static string LocationExist {
            get {
                return ResourceManager.GetString("LocationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location successfully added..
        /// </summary>
        internal static string LocationSuccessAdd {
            get {
                return ResourceManager.GetString("LocationSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location successfully updated..
        /// </summary>
        internal static string LocationSuccessUpdate {
            get {
                return ResourceManager.GetString("LocationSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ••••••••••••.
        /// </summary>
        internal static string NameMasked {
            get {
                return ResourceManager.GetString("NameMasked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-alphanumeric.
        /// </summary>
        internal static string NonAlphanumric {
            get {
                return ResourceManager.GetString("NonAlphanumric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non letter or digit.
        /// </summary>
        internal static string NonLetterOrDigit {
            get {
                return ResourceManager.GetString("NonLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLucent Password Reset.
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password email sent..
        /// </summary>
        internal static string PasswordResetEmailSent {
            get {
                return ResourceManager.GetString("PasswordResetEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link for reset of password is sent to your email..
        /// </summary>
        internal static string PasswordResetForgot {
            get {
                return ResourceManager.GetString("PasswordResetForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successful..
        /// </summary>
        internal static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture upload failed..
        /// </summary>
        internal static string ProfilePictureFailUpload {
            get {
                return ResourceManager.GetString("ProfilePictureFailUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture successfully uploaded..
        /// </summary>
        internal static string ProfilePictureSuccessUpload {
            get {
                return ResourceManager.GetString("ProfilePictureSuccessUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;REMINDER:&lt;/b&gt; Please check all agents and users under your supervision to ensure that they are displaying accurate information on their IOM status..
        /// </summary>
        internal static string RemAgentStatus {
            get {
                return ResourceManager.GetString("RemAgentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: Agent status.
        /// </summary>
        internal static string RemAgentStatusTitle {
            get {
                return ResourceManager.GetString("RemAgentStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;REMINDER:&lt;/b&gt; Please ensure that you have checked the attendance report and have corrected any discrepancies..
        /// </summary>
        internal static string RemAttendanceData {
            get {
                return ResourceManager.GetString("RemAttendanceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: Attendance Data.
        /// </summary>
        internal static string RemAttendanceDataTitle {
            get {
                return ResourceManager.GetString("RemAttendanceDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa-bell.
        /// </summary>
        internal static string ReminderIcon {
            get {
                return ResourceManager.GetString("ReminderIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role must be an Account Manager..
        /// </summary>
        internal static string RoleAccountManager {
            get {
                return ResourceManager.GetString("RoleAccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role must be an Agent..
        /// </summary>
        internal static string RoleAgent {
            get {
                return ResourceManager.GetString("RoleAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role must be a Client POC..
        /// </summary>
        internal static string RoleClient {
            get {
                return ResourceManager.GetString("RoleClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role must be a Lead Agent..
        /// </summary>
        internal static string RoleLA {
            get {
                return ResourceManager.GetString("RoleLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must be an agent..
        /// </summary>
        internal static string RuleUserAgent {
            get {
                return ResourceManager.GetString("RuleUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for reaching us. We will get back to you as soon as possible..
        /// </summary>
        internal static string SupportReplyMsg {
            get {
                return ResourceManager.GetString("SupportReplyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name already exists..
        /// </summary>
        internal static string TagDuplicateName {
            get {
                return ResourceManager.GetString("TagDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully added..
        /// </summary>
        internal static string TagSuccessAdd {
            get {
                return ResourceManager.GetString("TagSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully assigned..
        /// </summary>
        internal static string TagSuccessAssign {
            get {
                return ResourceManager.GetString("TagSuccessAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully deleted..
        /// </summary>
        internal static string TagSuccessDelete {
            get {
                return ResourceManager.GetString("TagSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully removed from assigment..
        /// </summary>
        internal static string TagSuccessRemove {
            get {
                return ResourceManager.GetString("TagSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag successfully updated..
        /// </summary>
        internal static string TagSuccessUpdate {
            get {
                return ResourceManager.GetString("TagSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} users is/are assigned to the task..
        /// </summary>
        internal static string TaskAssigneeAddStatus {
            get {
                return ResourceManager.GetString("TaskAssigneeAddStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal of assignee {0} from task has failed. The user is currently active with the task..
        /// </summary>
        internal static string TaskAssigneeRemovalError {
            get {
                return ResourceManager.GetString("TaskAssigneeRemovalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} users is/are removed from the task..
        /// </summary>
        internal static string TaskAssigneeRemoveStatus {
            get {
                return ResourceManager.GetString("TaskAssigneeRemoveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deactivate task, task is currently active..
        /// </summary>
        internal static string TaskDeactivateInUseTask {
            get {
                return ResourceManager.GetString("TaskDeactivateInUseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Correspondence, Task Review and general admin work.
        /// </summary>
        internal static string TaskDefaultDescAdmin {
            get {
                return ResourceManager.GetString("TaskDefaultDescAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus-Group Discussions and Team or Office Meeting.
        /// </summary>
        internal static string TaskDefaultDescMeeting {
            get {
                return ResourceManager.GetString("TaskDefaultDescMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training for new tasks, new staff, refresher or cross-training.
        /// </summary>
        internal static string TaskDefaultDescTraining {
            get {
                return ResourceManager.GetString("TaskDefaultDescTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string TaskDefaultNameAdmin {
            get {
                return ResourceManager.GetString("TaskDefaultNameAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        internal static string TaskDefaultNameMeeting {
            get {
                return ResourceManager.GetString("TaskDefaultNameMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string TaskDefaultNameTraining {
            get {
                return ResourceManager.GetString("TaskDefaultNameTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Description is too long, allowed characters is 250.
        /// </summary>
        internal static string TaskDescriptionTooLongErr {
            get {
                return ResourceManager.GetString("TaskDescriptionTooLongErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Group Created.
        /// </summary>
        internal static string TaskGroupCreated {
            get {
                return ResourceManager.GetString("TaskGroupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Group Deleted.
        /// </summary>
        internal static string TaskGroupDeleted {
            get {
                return ResourceManager.GetString("TaskGroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task group name is required..
        /// </summary>
        internal static string TaskGroupNameMissingErr {
            get {
                return ResourceManager.GetString("TaskGroupNameMissingErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Group successfully added..
        /// </summary>
        internal static string TaskGroupSuccessAdd {
            get {
                return ResourceManager.GetString("TaskGroupSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Group successfully deleted..
        /// </summary>
        internal static string TaskGroupSuccessRemove {
            get {
                return ResourceManager.GetString("TaskGroupSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Group Updated.
        /// </summary>
        internal static string TaskGroupUpdated {
            get {
                return ResourceManager.GetString("TaskGroupUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request, task is currently active.
        /// </summary>
        internal static string TaskIsActiveError {
            get {
                return ResourceManager.GetString("TaskIsActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name or Task Id already exist. Please pick a new one..
        /// </summary>
        internal static string TaskNameExist {
            get {
                return ResourceManager.GetString("TaskNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name is required..
        /// </summary>
        internal static string TaskNameMissingErr {
            get {
                return ResourceManager.GetString("TaskNameMissingErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name is too long, allowed characters is 150.
        /// </summary>
        internal static string TaskNameTooLongErr {
            get {
                return ResourceManager.GetString("TaskNameTooLongErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found..
        /// </summary>
        internal static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID must not exceed 12 characters.
        /// </summary>
        internal static string TaskNumberExceedsCharacterLimit {
            get {
                return ResourceManager.GetString("TaskNumberExceedsCharacterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task number is required..
        /// </summary>
        internal static string TaskNumberMissingErr {
            get {
                return ResourceManager.GetString("TaskNumberMissingErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully added..
        /// </summary>
        internal static string TaskSuccessAdd {
            get {
                return ResourceManager.GetString("TaskSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully assigned to a team..
        /// </summary>
        internal static string TaskSuccessAssign {
            get {
                return ResourceManager.GetString("TaskSuccessAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully deleted..
        /// </summary>
        internal static string TaskSuccessDelete {
            get {
                return ResourceManager.GetString("TaskSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully remove from a team..
        /// </summary>
        internal static string TaskSuccessRemove {
            get {
                return ResourceManager.GetString("TaskSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully updated..
        /// </summary>
        internal static string TaskSuccessUpdate {
            get {
                return ResourceManager.GetString("TaskSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Manager(s) successfully added..
        /// </summary>
        internal static string TeamManagerSuccessAdd {
            get {
                return ResourceManager.GetString("TeamManagerSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Manager successfully removed.
        /// </summary>
        internal static string TeamManagerSuccessRemove {
            get {
                return ResourceManager.GetString("TeamManagerSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name already exist. Please pick a new one..
        /// </summary>
        internal static string TeamNameExist {
            get {
                return ResourceManager.GetString("TeamNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found..
        /// </summary>
        internal static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team successfully activated..
        /// </summary>
        internal static string TeamSuccessActivate {
            get {
                return ResourceManager.GetString("TeamSuccessActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team successfully added..
        /// </summary>
        internal static string TeamSuccessAdd {
            get {
                return ResourceManager.GetString("TeamSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team successfully deactivated..
        /// </summary>
        internal static string TeamSuccessDeactivate {
            get {
                return ResourceManager.GetString("TeamSuccessDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team successfully deleted..
        /// </summary>
        internal static string TeamSuccessDelete {
            get {
                return ResourceManager.GetString("TeamSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team successfully updated..
        /// </summary>
        internal static string TeamSuccessUpdate {
            get {
                return ResourceManager.GetString("TeamSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated Day-Offs &amp; Holidays.
        /// </summary>
        internal static string TeamUpdateDOHSuccess {
            get {
                return ResourceManager.GetString("TeamUpdateDOHSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you from iLucent.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh:mm tt.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete task because it associated with data in the time keeping history..
        /// </summary>
        internal static string UnableToDeleteTask {
            get {
                return ResourceManager.GetString("UnableToDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized for this request..
        /// </summary>
        internal static string User401 {
            get {
                return ResourceManager.GetString("User401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user_deleted.
        /// </summary>
        internal static string UserDeletedkey {
            get {
                return ResourceManager.GetString("UserDeletedkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account has been deleted..
        /// </summary>
        internal static string UserDeletedMsg {
            get {
                return ResourceManager.GetString("UserDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid_grant.
        /// </summary>
        internal static string UserInvalidKey {
            get {
                return ResourceManager.GetString("UserInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        internal static string UserInvalidMsg {
            get {
                return ResourceManager.GetString("UserInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to access IOM from an unauthorized location. Please contact your supervisor or manager..
        /// </summary>
        internal static string UserIPRestricted {
            get {
                return ResourceManager.GetString("UserIPRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserIPRestricted.
        /// </summary>
        internal static string UserIPRestrictedKEy {
            get {
                return ResourceManager.GetString("UserIPRestrictedKEy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user_locked.
        /// </summary>
        internal static string UserLockedKey {
            get {
                return ResourceManager.GetString("UserLockedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account has been locked please contact your System Administrator..
        /// </summary>
        internal static string UserLockedMsg {
            get {
                return ResourceManager.GetString("UserLockedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift detail sucessfully updated..
        /// </summary>
        internal static string UserShiftSuccessUpdate {
            get {
                return ResourceManager.GetString("UserShiftSuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s assigned account successfully updated..
        /// </summary>
        internal static string UserSuccessAccountChange {
            get {
                return ResourceManager.GetString("UserSuccessAccountChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully added.
        /// </summary>
        internal static string UserSuccessAdd {
            get {
                return ResourceManager.GetString("UserSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created..
        /// </summary>
        internal static string UserSuccessCreate {
            get {
                return ResourceManager.GetString("UserSuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted..
        /// </summary>
        internal static string UserSuccessDelete {
            get {
                return ResourceManager.GetString("UserSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deactivated.
        /// </summary>
        internal static string UserSuccessLock {
            get {
                return ResourceManager.GetString("UserSuccessLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully removed.
        /// </summary>
        internal static string UserSuccessRemove {
            get {
                return ResourceManager.GetString("UserSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status successfully changed..
        /// </summary>
        internal static string UserSuccessStatusChange {
            get {
                return ResourceManager.GetString("UserSuccessStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s assigned teams successfully updated..
        /// </summary>
        internal static string UserSuccessTeamsChange {
            get {
                return ResourceManager.GetString("UserSuccessTeamsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully activated..
        /// </summary>
        internal static string UserSuccessUnlock {
            get {
                return ResourceManager.GetString("UserSuccessUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User detail updated successfully..
        /// </summary>
        internal static string UserSuccessUpdateDetail {
            get {
                return ResourceManager.GetString("UserSuccessUpdateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update user task notification..
        /// </summary>
        internal static string UserTaskNotificationUpdateError {
            get {
                return ResourceManager.GetString("UserTaskNotificationUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User task notification successfully updated..
        /// </summary>
        internal static string UserTaskNotificationUpdateSuccess {
            get {
                return ResourceManager.GetString("UserTaskNotificationUpdateSuccess", resourceCulture);
            }
        }
    }
}
