//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EODTaskItem
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public decimal TotalTaskHours { get; set; }
        public decimal AdjustedTotalHours { get; set; }
        public int EODReportId { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public Nullable<bool> IsInserted { get; set; }
    }
}
