//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public int ModuleId { get; set; }
        public bool IsLocked { get; set; }
        public bool CanView { get; set; }
        public bool CanAdd { get; set; }
        public bool CanEdit { get; set; }
        public bool CanDelete { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ModuleCode { get; set; }
    
        public virtual AspNetModule AspNetModule { get; set; }
        public virtual AspNetRole AspNetRole { get; set; }
    }
}
