//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int Id { get; set; }
        public System.DateTime LogDate { get; set; }
        public int ActorUserId { get; set; }
        public string RawUrl { get; set; }
        public string ActionType { get; set; }
        public string Description { get; set; }
        public string Entity { get; set; }
        public string BrowserUsed { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> ElapseTime { get; set; }
        public Nullable<int> ResponseStatusCode { get; set; }
        public string UrlParams { get; set; }
        public string RequestBody { get; set; }
        public string Note { get; set; }
        public string EODEmailReference { get; set; }
    }
}
