//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public int UserDetailsId { get; set; }
        public System.DateTime HistoryDate { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public bool IsActive { get; set; }
        public int TaskHistoryTypeId { get; set; }
        public Nullable<System.DateTime> ActivateTime { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual TaskHistoryType TaskHistoryType { get; set; }
    }
}
