//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDayOff
    {
        public int Id { get; set; }
        public int UserDetailsId { get; set; }
        public string Day { get; set; }
        public int NumericDay { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
