//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTask
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int TaskId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual IOMTask IOMTask { get; set; }
        public virtual TaskGroup TaskGroup { get; set; }
        public virtual Team Team { get; set; }
    }
}
