//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AgentTeamSupervisors
    {
        public string UserUniqueId { get; set; }
        public int UserDetailsId { get; set; }
        public string Fullname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Role { get; set; }
        public string RoleName { get; set; }
        public string Image { get; set; }
        public string AccountIds { get; set; }
        public string TeamIds { get; set; }
    }
}
