//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOM.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AttendanceDefaultView
    {
        public int UserDetailsId { get; set; }
        public Nullable<decimal> TotalActiveTime { get; set; }
        public System.DateTime HistoryDate { get; set; }
        public Nullable<decimal> RegularHours { get; set; }
        public Nullable<decimal> OTHours { get; set; }
    }
}
