CREATE TABLE [dbo].[IOMTeamTask](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TeamId] [int] NOT NULL,
	[TaskId] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_IOMTeamTask] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[IOMTeamTask]  WITH CHECK ADD  CONSTRAINT [FK_IOMTeamTask_IOMTasks] FOREIGN KEY([TaskId])
REFERENCES [dbo].[IOMTasks] ([Id])
GO

ALTER TABLE [dbo].[IOMTeamTask] CHECK CONSTRAINT [FK_IOMTeamTask_IOMTasks]
GO

ALTER TABLE [dbo].[IOMTeamTask]  WITH CHECK ADD  CONSTRAINT [FK_IOMTeamTask_Teams] FOREIGN KEY([TeamId])
REFERENCES [dbo].[Teams] ([Id])
GO

ALTER TABLE [dbo].[IOMTeamTask] CHECK CONSTRAINT [FK_IOMTeamTask_Teams]
GO
